---
- name: Get Vector distrib          # Скачиваем Vector
  become: true
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector_{{ vector_version }}-1_amd64.deb"
    dest: "/tmp/vector.deb"
    mode: '644'
- name: Install Vector packages     # Устанавливаем Vector
  become: true
  ansible.builtin.apt:
    deb: "/tmp/vector.deb"
  notify: Start vector service
- name: Vector config               # Настраиваем Vector
  become: true
  ansible.builtin.template:
    src: templates/vector.yml.j2
    dest: /etc/vector/vector.yaml
    mode: '644'
  tags: config_vector
  notify: Start vector service
- name: Flush handlers
  ansible.builtin.meta: flush_handlers