---
- name: Start vector service
  ansible.builtin.service:
    name: vector
    state: restarted
- name: Get Vector version          # Проверяемм наличие Vector в системе
  ansible.builtin.command: vector --version
  register: is_installed
  changed_when: is_installed.rc != 0
  notify: Restart vector